import type { Ticket, User } from './types';

export const mockUsers: User[] = [
  { id: 'user-1', name: 'Alice', email: 'alice@example.com' },
  { id: 'user-2', name: 'Bob', email: 'bob@example.com' },
  { id: 'user-3', name: 'Charlie', email: 'charlie@example.com' },
];

export const mockTickets: Ticket[] = [
  {
    id: 'ticket-1',
    movieName: 'Dune: Part Two',
    theaterName: 'Cineplex Odeon',
    location: 'Toronto, ON',
    showDate: '2024-10-26',
    showTime: '19:00',
    ticketCount: 2,
    price: 35.00,
    imageUrl: 'https://picsum.photos/seed/movie1/400/600',
    imageHint: 'sci-fi movie',
    postedBy: 'user-1',
    status: 'available',
  },
  {
    id: 'ticket-2',
    movieName: 'Furiosa: A Mad Max Saga',
    theaterName: 'Scotiabank Theatre',
    location: 'Vancouver, BC',
    showDate: '2024-10-27',
    showTime: '20:30',
    ticketCount: 4,
    price: 28.00,
    imageUrl: 'https://picsum.photos/seed/movie2/400/600',
    imageHint: 'action movie',
    postedBy: 'user-2',
    status: 'available',
  },
  {
    id: 'ticket-3',
    movieName: 'Inside Out 2',
    theaterName: 'Landmark Cinemas',
    location: 'Calgary, AB',
    showDate: '2024-10-26',
    showTime: '15:00',
    ticketCount: 3,
    price: 22.50,
    imageUrl: 'https://picsum.photos/seed/movie3/400/600',
    imageHint: 'animated movie',
    postedBy: 'user-1',
    status: 'available',
  },
    {
    id: 'ticket-4',
    movieName: 'A Quiet Place: Day One',
    theaterName: 'SilverCity Cinemas',
    location: 'Toronto, ON',
    showDate: '2024-10-28',
    showTime: '22:00',
    ticketCount: 1,
    price: 18.50,
    imageUrl: 'https://picsum.photos/seed/movie4/400/600',
    imageHint: 'horror movie',
    postedBy: 'user-2',
    status: 'available',
  },
  {
    id: 'ticket-5',
    movieName: 'Joker: Folie à Deux',
    theaterName: 'Cineplex Odeon',
    location: 'Montreal, QC',
    showDate: '2024-11-01',
    showTime: '21:00',
    ticketCount: 2,
    price: 50.00,
    imageUrl: 'https://picsum.photos/seed/movie5/400/600',
    imageHint: 'thriller movie',
    postedBy: 'user-3',
    status: 'sold',
  },
  {
    id: 'ticket-6',
    movieName: 'Gladiator 2',
    theaterName: 'IMAX Cinemas',
    location: 'New York, NY',
    showDate: '2024-11-22',
    showTime: '18:00',
    ticketCount: 2,
    price: 60.00,
    imageUrl: 'https://picsum.photos/seed/movie6/400/600',
    imageHint: 'historical drama',
    postedBy: 'user-1',
    status: 'available',
  },
];
